/**
 * The six starter recipes. Quantities are stored as a number plus a unit so the
 * servings scaler in Phase 3 can do arithmetic on them; a null qty means the
 * amount is not scalable ("to taste", "a handful").
 */
export const recipes = [
  {
    slug: "chicken-pasta",
    title: "Chicken Pasta of your Dreams",
    category: "Pasta",
    description:
      "For all those times you've just gotta have a creamy pasta! Tender chicken breast in a rich garlic parmesan sauce that coats every strand of fettuccine — the kind of comfort food that makes you close your eyes on the first bite.",
    image_url: "assets/img/chicken-pasta.jpg",
    time_minutes: 55,
    servings: 4,
    difficulty: "Medium",
    featured: 1,
    ingredients: [
      ["🍗", "Chicken Breast", 500, "g"],
      ["🍝", "Fettuccine Pasta", 400, "g"],
      ["🧄", "Garlic (minced)", 4, "cloves"],
      ["🧀", "Parmesan Cheese", 1, "cup"],
      ["🥛", "Heavy Cream", 250, "ml"],
      ["🧈", "Butter", 2, "tbsp"],
      ["🫒", "Olive Oil", 2, "tbsp"],
      ["🌶️", "Paprika", 1, "tsp"],
      ["🌿", "Fresh Basil", null, "a handful"],
      ["🧂", "Salt & Pepper", null, "to taste"],
    ],
    steps: [
      "Season the chicken breasts with salt, pepper and a pinch of paprika. Heat the olive oil in a large skillet over medium-high heat.",
      "Cook the chicken for 6–7 minutes per side until golden and cooked through. Remove from the pan and let it rest, then slice into strips.",
      "While the chicken rests, cook the fettuccine in a large pot of salted boiling water according to the package directions. Drain, reserving 1 cup of pasta water.",
      "In the same skillet, melt the butter over medium heat. Add the minced garlic and sauté for 1 minute until fragrant.",
      "Pour in the heavy cream and bring to a gentle simmer. Stir in the parmesan until melted and smooth, loosening with pasta water as needed.",
      "Toss the pasta through the sauce, top with the sliced chicken and torn basil, and serve immediately with extra parmesan.",
    ],
  },
  {
    slug: "beef-bourguignon",
    title: "Beef Bourguignon",
    category: "Stews",
    description:
      "The best beef stew in the world. Full stop! Beef chuck braised slowly in red Burgundy with bacon, pearl onions and mushrooms, until the sauce turns glossy and the meat gives way to a fork.",
    image_url: "assets/img/beef-bourguignon.jpg",
    time_minutes: 210,
    servings: 6,
    difficulty: "Hard",
    featured: 1,
    ingredients: [
      ["🥩", "Beef Chuck (cubed)", 1.5, "kg"],
      ["🥓", "Smoked Bacon (diced)", 200, "g"],
      ["🍷", "Red Burgundy Wine", 750, "ml"],
      ["🥣", "Beef Stock", 500, "ml"],
      ["🥕", "Carrots (thickly sliced)", 4, null],
      ["🧅", "Pearl Onions", 300, "g"],
      ["🍄", "Button Mushrooms", 400, "g"],
      ["🧄", "Garlic (crushed)", 4, "cloves"],
      ["🍅", "Tomato Paste", 2, "tbsp"],
      ["🌾", "Plain Flour", 3, "tbsp"],
      ["🧈", "Butter", 3, "tbsp"],
      ["🌿", "Thyme and Bay", null, "a few sprigs"],
      ["🧂", "Salt & Pepper", null, "to taste"],
    ],
    steps: [
      "Pat the beef thoroughly dry and season it generously. Dry meat browns; wet meat steams.",
      "Render the bacon in a heavy casserole over medium heat until crisp, then lift it out and leave the fat behind.",
      "Brown the beef in that fat in batches, about 3 minutes a side, never crowding the pan. Set it aside with the bacon.",
      "Soften the carrots and crushed garlic in the same pot, then stir in the tomato paste and cook for a minute until it darkens.",
      "Sprinkle over the flour and stir for 2 minutes, then pour in the wine and stock, scraping every brown bit off the base.",
      "Return the beef and bacon with the thyme and bay. Cover and cook at 160°C / 325°F for 2½ hours, until a fork meets no resistance.",
      "Meanwhile, brown the pearl onions and mushrooms in the butter in a separate pan until deeply coloured.",
      "Stir them in for the last 15 minutes, fish out the herbs, taste for salt, and serve with mash or crusty bread.",
    ],
  },
  {
    slug: "carrot-cake",
    title: "Carrot Cake",
    category: "Cakes",
    description:
      "Can't get enough of this cake — the cream cheese frosting has something to do with it! Deeply spiced, properly moist, and studded with walnuts for a bit of crunch against the soft crumb.",
    image_url: "assets/img/carrot-cake.svg",
    time_minutes: 75,
    servings: 12,
    difficulty: "Easy",
    featured: 1,
    ingredients: [
      ["🥕", "Carrots (finely grated)", 400, "g"],
      ["🌾", "Plain Flour", 300, "g"],
      ["🍚", "Light Brown Sugar", 300, "g"],
      ["🥚", "Eggs", 4, null],
      ["🫒", "Sunflower Oil", 250, "ml"],
      ["🥄", "Baking Powder", 2, "tsp"],
      ["🥄", "Bicarbonate of Soda", 1, "tsp"],
      ["🧂", "Ground Cinnamon", 2, "tsp"],
      ["🌰", "Walnuts (chopped)", 100, "g"],
      ["🧀", "Cream Cheese", 300, "g"],
      ["🧈", "Butter (softened)", 100, "g"],
      ["🍥", "Icing Sugar", 200, "g"],
    ],
    steps: [
      "Heat the oven to 180°C / 350°F and line two 20 cm round tins.",
      "Whisk the eggs, brown sugar and oil for about 2 minutes, until smooth and a shade paler.",
      "Sift in the flour, baking powder, bicarbonate of soda and cinnamon, and fold just until no dry flour remains — overmixing makes it tough.",
      "Fold through the grated carrot and most of the walnuts, holding a handful back for the top.",
      "Divide between the tins and bake for 30–35 minutes, until a skewer comes out clean. Cool completely in the tins.",
      "Beat the butter and icing sugar smooth, then add the cream cheese and beat only until combined; keep going and it will loosen.",
      "Sandwich the layers with a third of the frosting, spread the rest over the top, and scatter over the reserved walnuts.",
    ],
  },
  {
    slug: "rosemary-chicken",
    title: "Rosemary Chicken",
    category: "Poultry",
    description:
      "Bone-in thighs roasted over baby potatoes with rosemary, garlic and lemon. Everything cooks in one tin, the skin goes crisp, and the potatoes soak up all the juices.",
    image_url: "assets/img/rosemary-chicken.jpg",
    time_minutes: 45,
    servings: 4,
    difficulty: "Easy",
    featured: 0,
    ingredients: [
      ["🍗", "Chicken Thighs (bone-in)", 8, null],
      ["🥔", "Baby Potatoes", 800, "g"],
      ["🌿", "Fresh Rosemary", 4, "sprigs"],
      ["🧄", "Garlic (halved head)", 1, "head"],
      ["🍋", "Lemon", 1, null],
      ["🫒", "Olive Oil", 3, "tbsp"],
      ["🧂", "Flaky Salt & Pepper", null, "to taste"],
    ],
    steps: [
      "Heat the oven to 200°C / 400°F. Halve the potatoes and toss them with the oil, half the rosemary and plenty of salt in a large roasting tin.",
      "Season the thighs on both sides and nestle them skin-side up among the potatoes.",
      "Tuck the garlic halves and remaining rosemary into the gaps, then roast for 25 minutes.",
      "Squeeze over half the lemon, spoon the pan juices back over the skin, and roast for a further 10–15 minutes until deep gold and the juices run clear.",
      "Rest for 5 minutes in the tin so the juices settle back into the meat.",
      "Squeeze over the rest of the lemon, scrape the sticky bits off the tin, and serve straight from the pan.",
    ],
  },
  {
    slug: "wagyu-ribeye",
    title: "Grilled Wagyu Ribeye",
    category: "Beef",
    description:
      "A thick ribeye, a very hot grill and almost nothing else — the marbling does the work. Finished with thyme butter and rested properly, which matters more than anything you do to it in the pan.",
    image_url: "assets/img/wagyu-ribeye.jpg",
    time_minutes: 30,
    servings: 2,
    difficulty: "Medium",
    featured: 0,
    ingredients: [
      ["🥩", "Wagyu Ribeye (3 cm thick)", 2, "steaks"],
      ["🧈", "Butter", 50, "g"],
      ["🌿", "Thyme", 4, "sprigs"],
      ["🧄", "Garlic (crushed)", 2, "cloves"],
      ["🧂", "Flaky Sea Salt", null, "to taste"],
      ["🌶️", "Cracked Black Pepper", null, "to taste"],
    ],
    steps: [
      "Take the steaks out of the fridge 30 minutes ahead and salt them generously on both sides. Cold meat cooks unevenly.",
      "Get the grill or a cast-iron pan as hot as it will go — just short of smoking.",
      "Pat the surface dry, then sear for 2 minutes without moving it, until a dark crust forms.",
      "Flip, add the butter, thyme and garlic, and baste continuously for another 2–3 minutes for medium-rare (52°C / 125°F in the centre).",
      "Rest on a warm plate for at least 5 minutes — as long as it cooked, if you can wait that long.",
      "Slice against the grain, spoon over the resting juices and thyme butter, and finish with cracked pepper.",
    ],
  },
  {
    slug: "vegetable-tartine",
    title: "Roasted Vegetable Tartine",
    category: "Vegetarian",
    description:
      "Thick sourdough piled with sweet, properly caramelised roasted vegetables and whipped goat cheese, finished with honey and torn basil. Best eaten with your hands.",
    image_url: "assets/img/vegetable-tartine.jpg",
    time_minutes: 50,
    servings: 4,
    difficulty: "Easy",
    featured: 0,
    ingredients: [
      ["🍞", "Sourdough (thick slices)", 4, null],
      ["🍆", "Aubergine", 1, null],
      ["🫑", "Red Peppers", 2, null],
      ["🥒", "Courgette", 1, null],
      ["🧅", "Red Onion", 1, null],
      ["🧀", "Soft Goat Cheese", 200, "g"],
      ["🫒", "Olive Oil", 4, "tbsp"],
      ["🍯", "Honey", 1, "tbsp"],
      ["🌿", "Fresh Basil", null, "a handful"],
      ["🧂", "Salt & Pepper", null, "to taste"],
    ],
    steps: [
      "Heat the oven to 220°C / 425°F. Cut all the vegetables into rough 3 cm pieces so they roast at the same rate.",
      "Toss with 3 tbsp of the oil and plenty of salt, then spread over two trays rather than one — crowded vegetables steam instead of caramelising.",
      "Roast for 30 minutes, turning once, until the edges are properly browned.",
      "Meanwhile whip the goat cheese with a splash of water until spreadable, and toast the sourdough.",
      "Rub the warm toast with the remaining oil, spread thickly with the goat cheese, and pile the vegetables on top.",
      "Drizzle with honey, tear over the basil, and finish with cracked pepper.",
    ],
  },
];
